### ISSUE TITLE
Should make distclean delete more stuff?

### ISSUE THREAD

**Issue by wilfwilson** [semigroups/Semigroups#724]
I've not been able to compile the development version of the Semigroups package for ages. Since I've not been actively developing for the Semigroups package, this hasn't been a huge problem, because I have just used the released version: I can download the `v3.4.0` release of Semigroups from GitHub and compile and load it fine.  This suggests to me that my system isn't completely crazy. (FYI I'm on macOS 10.13.6, compiling with `Apple LLVM version 10.0.0 (clang-1000.10.44.4)`).

I couldn't get the Semigroups package to compile with my GitHub copy of Semigroups at `master`, `stable-3.4` or `v3.4.0`, and with `libsemigroups` being the actual `v1.3.2` release (I think), or a GitHub clone at any of the tags `v1.3.2`, `v1.3.3`, or `v1.3.4`. I've included the compilation error I was getting at the end, in case you are interested (it's something to do with `UF`).

However, I realised that I could get a development version to compile by freshly cloning the Semigroups repo! Weird - because surely there should be no difference between an old repo and a newly cloned repo that both point at the same commit (and yes, I was running `make distclean`, `autogen.sh`, etc., as appropriate).

I decided to run `diff --recursive` to compare my old clone (after running `make distclean`) and a brand new uncompiled clone. I got all of this unexpected stuff:
```
Only in OLDCLONE: Makefile.in
Only in OLDCLONE: aclocal.m4
Only in OLDCLONE: autom4te.cache
Only in OLDCLONE: bin/
Only in OLDCLONE: cnf/
Only in OLDCLONE: configure
Only in OLDCLONE/m4: libtool.m4
Only in OLDCLONE/m4: ltoptions.m4
Only in OLDCLONE/m4: ltsugar.m4
Only in OLDCLONE/m4: ltversion.m4
Only in OLDCLONE/m4: lt~obsolete.m4
Only in OLDCLONE/src: .deps/
Only in OLDCLONE/src: semigroups-config.h
```
After deleting this stuff manually, I finally got my old clone of Semigroups to compile for the first time in months! I'm not sure what was causing the problem precisely, but I'd guess something in `cnf` or `src/.deps` or `src/semigroups-config.h` being out of date?

My understanding is that `make distclean` should return the directory to the freshly-cloned stated, so I don't think there should have been anything shown by `diff` (except for the `.git` and `libsemigroups` folders, which I omitted above).

**So this indicates to me that `make distclean` should be deleting more (or all?) of the stuff listed above.** I'm pretty ignorant of how all this compilation stuff works, however. Perhaps the appendix will indicate what should have been deleted that wasn't.

### Appendix: the problem I was getting:
```
./prerequisites.sh && ./autogen.sh && ./configure && make -j8
```
...and it all goes fine until the actual compilation...
```
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in libsemigroups
make[2]: Nothing to be done for `all'.
  CXX      src/semigroups_la-pkg.lo
  CXX      src/semigroups_la-converter.lo
  CXX      src/semigroups_la-bipart.lo
  CXX      src/semigroups_la-uf.lo
  CXX      src/semigroups_la-fropin.lo
  CXX      src/semigroups_la-congpairs.lo
  CXX      src/semigroups_la-semigrp.lo
src/uf.cc:37:24: error: use of class template 'UF' requires template arguments
  return OBJ_CLASS(new UF(INT_INTOBJ(size)), T_SEMI_SUBTYPE_UF);
                       ^
./bin/include/libsemigroups/uf.hpp:54:11: note: template is declared here
    class UF {
          ^
src/uf.cc:41:24: error: use of class template 'UF' requires template arguments
  return OBJ_CLASS(new UF(*CLASS_OBJ<UF*>(uf)), T_SEMI_SUBTYPE_UF);
                       ^
./bin/include/libsemigroups/uf.hpp:54:11: note: template is declared here
    class UF {
          ^
src/uf.cc:45:31: error: cannot refer to class template 'UF' without a template
      argument list
  return INTOBJ_INT(CLASS_OBJ<UF*>(uf)->get_size());
                              ^
./bin/include/libsemigroups/uf.hpp:54:11: note: template is declared here
    class UF {
          ^
src/uf.cc:45:34: error: expected expression
  return INTOBJ_INT(CLASS_OBJ<UF*>(uf)->get_size());
                                 ^
src/uf.cc:50:31: error: cannot refer to class template 'UF' without a template
      argument list
  return INTOBJ_INT(CLASS_OBJ<UF*>(uf)->find(INT_INTOBJ(i) - 1) + 1);
                              ^
./bin/include/libsemigroups/uf.hpp:54:11: note: template is declared here
    class UF {
          ^
src/uf.cc:50:34: error: expected expression
  return INTOBJ_INT(CLASS_OBJ<UF*>(uf)->find(INT_INTOBJ(i) - 1) + 1);
                                 ^
src/uf.cc:59:13: error: cannot refer to class template 'UF' without a template
      argument list
  CLASS_OBJ<UF*>(uf)->unite(INT_INTOBJ(ELM_PLIST(pair, 1)) - 1,
            ^
./bin/include/libsemigroups/uf.hpp:54:11: note: template is declared here
    class UF {
          ^
src/uf.cc:59:16: error: expected expression
  CLASS_OBJ<UF*>(uf)->unite(INT_INTOBJ(ELM_PLIST(pair, 1)) - 1,
               ^
src/uf.cc:65:13: error: cannot refer to class template 'UF' without a template
      argument list
  CLASS_OBJ<UF*>(uf)->flatten();
            ^
./bin/include/libsemigroups/uf.hpp:54:11: note: template is declared here
    class UF {
          ^
src/uf.cc:65:16: error: expected expression
  CLASS_OBJ<UF*>(uf)->flatten();
               ^
src/uf.cc:70:3: error: 'UF' is not a class, namespace, or enumeration
  UF::table_type* table     = CLASS_OBJ<UF*>(uf)->get_table();
  ^
./bin/include/libsemigroups/uf.hpp:54:11: note: 'UF' declared here
    class UF {
          ^
src/uf.cc:70:41: error: cannot refer to class template 'UF' without a template
      argument list
  UF::table_type* table     = CLASS_OBJ<UF*>(uf)->get_table();
                                        ^
./bin/include/libsemigroups/uf.hpp:54:11: note: template is declared here
    class UF {
          ^
src/uf.cc:70:44: error: expected expression
  UF::table_type* table     = CLASS_OBJ<UF*>(uf)->get_table();
                                           ^
src/uf.cc:82:3: error: 'UF' is not a class, namespace, or enumeration
  UF::blocks_type const* blocks = CLASS_OBJ<UF*>(uf)->get_blocks();
  ^
./bin/include/libsemigroups/uf.hpp:54:11: note: 'UF' declared here
    class UF {
          ^
src/uf.cc:82:19: error: expected unqualified-id
  UF::blocks_type const* blocks = CLASS_OBJ<UF*>(uf)->get_blocks();
                  ^
src/uf.cc:83:35: error: use of undeclared identifier 'blocks'
  size_t                 size   = blocks->size();
                                  ^
src/uf.cc:90:11: error: use of undeclared identifier 'blocks'
    if ((*blocks)[i] != nullptr) {  // nullptr represents a hole in the list
          ^
src/uf.cc:91:44: error: use of undeclared identifier 'blocks'
      Obj block = NEW_PLIST(T_PLIST_CYC, (*blocks)[i]->size());
                                           ^
src/uf.cc:92:30: error: use of undeclared identifier 'blocks'
      SET_LEN_PLIST(block, (*blocks)[i]->size());
                             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [src/semigroups_la-uf.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
src/semigrp.cc:1312:17: warning: 'reset_next_relation' is deprecated
      [-Wdeprecated-declarations]
      semi_cpp->reset_next_relation();
                ^
./bin/include/libsemigroups/froidure-pin-base.hpp:627:5: note:
      'reset_next_relation' has been explicitly marked deprecated here
    LIBSEMIGROUPS_DEPRECATED void reset_next_relation() noexcept {
    ^
./bin/include/libsemigroups/deprecated.hpp:23:49: note: expanded from macro
      'LIBSEMIGROUPS_DEPRECATED'
#define LIBSEMIGROUPS_DEPRECATED __attribute__((deprecated))
                                                ^
src/semigrp.cc:1314:17: warning: 'next_relation' is deprecated
      [-Wdeprecated-declarations]
      semi_cpp->next_relation(relation);
                ^
./bin/include/libsemigroups/froidure-pin-base.hpp:667:5: note: 'next_relation'
      has been explicitly marked deprecated here
    LIBSEMIGROUPS_DEPRECATED void next_relation(word_type& relation);
    ^
./bin/include/libsemigroups/deprecated.hpp:23:49: note: expanded from macro
      'LIBSEMIGROUPS_DEPRECATED'
#define LIBSEMIGROUPS_DEPRECATED __attribute__((deprecated))
                                                ^
src/semigrp.cc:1331:19: warning: 'next_relation' is deprecated
      [-Wdeprecated-declarations]
        semi_cpp->next_relation(relation);
                  ^
./bin/include/libsemigroups/froidure-pin-base.hpp:667:5: note: 'next_relation'
      has been explicitly marked deprecated here
    LIBSEMIGROUPS_DEPRECATED void next_relation(word_type& relation);
    ^
./bin/include/libsemigroups/deprecated.hpp:23:49: note: expanded from macro
      'LIBSEMIGROUPS_DEPRECATED'
#define LIBSEMIGROUPS_DEPRECATED __attribute__((deprecated))
                                                ^
src/semigrp.cc:1360:19: warning: 'next_relation' is deprecated
      [-Wdeprecated-declarations]
        semi_cpp->next_relation(relation);
                  ^
./bin/include/libsemigroups/froidure-pin-base.hpp:667:5: note: 'next_relation'
      has been explicitly marked deprecated here
    LIBSEMIGROUPS_DEPRECATED void next_relation(word_type& relation);
    ^
./bin/include/libsemigroups/deprecated.hpp:23:49: note: expanded from macro
      'LIBSEMIGROUPS_DEPRECATED'
#define LIBSEMIGROUPS_DEPRECATED __attribute__((deprecated))
                                                ^
src/pkg.cc:106:24: error: cannot refer to class template 'UF' without a template
      argument list
      delete CLASS_OBJ<UF*>(o);
                       ^
./bin/include/libsemigroups/uf.hpp:54:11: note: template is declared here
    class UF {
          ^
src/pkg.cc:106:27: error: expected expression
      delete CLASS_OBJ<UF*>(o);
                          ^
src/pkg.cc:161:7: error: use of class template 'UF' requires template arguments
      UF* uf = CLASS_OBJ<UF*>(o);
      ^
./bin/include/libsemigroups/uf.hpp:54:11: note: template is declared here
    class UF {
          ^
src/pkg.cc:161:26: error: cannot refer to class template 'UF' without a template
      argument list
      UF* uf = CLASS_OBJ<UF*>(o);
                         ^
./bin/include/libsemigroups/uf.hpp:54:11: note: template is declared here
    class UF {
          ^
src/pkg.cc:161:29: error: expected expression
      UF* uf = CLASS_OBJ<UF*>(o);
                            ^
src/pkg.cc:200:50: error: use of class template 'UF' requires template arguments
      ADDR_OBJ(o)[1] = reinterpret_cast<Obj>(new UF(*table));
                                                 ^
./bin/include/libsemigroups/uf.hpp:54:11: note: template is declared here
    class UF {
          ^
6 errors generated.
make[2]: *** [src/semigroups_la-pkg.lo] Error 1
4 warnings generated.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by james-d-mitchell** [comment]
@wilfwilson, the current release version of libsemigroups (v1.3.4) is incompatible with GAP Semigroups at present (bad I know, working to fix this as fast as I can!). But v1.3.3 should work no problems. There's some issues related to the changes introduced in https://github.com/semigroups/Semigroups/pull/584 (possibly, it might also be that the issues came from somewhere else). The fix apparently is to `rm -rf bin` in the `semigroups` pkg folder. I haven't investigated how to fix this properly, but somehow when you update `libsemigroups` it is not always `make install`ed into `bin` and so Semigroups uses the old version of `libsemigroups` inside the `bin` directory instead of the one inside the `libsemigroups` directory. This has tripped me up a number of times recently too.

**Comment by wilfwilson** [comment]
Ah right, thank you for the explanation! I probably tried to compile Semigroups with a bad version of libsemigroups one time. 

If you think there's a good reason, and a sensible way, to delete the files I mentioned above with a `make` target, then go ahead. Otherwise I'm happy enough to delete stuff manually if I get this problem again.

Feel free to close the issue as you think appropriate.

**Comment by james-d-mitchell** [comment]
I think this make target already exists, `make superclean` deletes all files not tracked by git from the repo. There should be a better solution though but I haven't thought it through yet.

**Comment by wilfwilson** [comment]
Brilliant, thanks.
