### PR TITLE
Release candidate for v5.5.1

### LINKED ISSUE #1064: Build problem on Mac OS
Semigroups packages fails to build on Mac OS 15.5.
Compiler:
```
Apple clang version 17.0.0 (clang-1700.0.13.5)
Target: arm64-apple-darwin24.5.0
Thread model: posix
```
Error message:
```
 make
./config.status gen/pkgconfig.h
config.status: creating gen/pkgconfig.h
config.status: gen/pkgconfig.h is unchanged
echo > gen/pkgconfig.h.stamp
   GAC     src/bipart.cpp => gen/src/bipart.o
   GAC     src/cong.cpp => gen/src/cong.o
   GAC     src/conglatt.cpp => gen/src/conglatt.o
   GAC     src/froidure-pin-base.cpp => gen/src/froidure-pin-base.o
   GAC     src/froidure-pin-bipart.cpp => gen/src/froidure-pin-bipart.o
   GAC     src/froidure-pin-bmat.cpp => gen/src/froidure-pin-bmat.o
   GAC     src/froidure-pin-fallback.cpp => gen/src/froidure-pin-fallback.o
   GAC     src/froidure-pin-matrix.cpp => gen/src/froidure-pin-matrix.o
   GAC     src/froidure-pin-max-plus-mat.cpp => gen/src/froidure-pin-max-plus-mat.o
   GAC     src/froidure-pin-min-plus-mat.cpp => gen/src/froidure-pin-min-plus-mat.o
   GAC     src/froidure-pin-pbr.cpp => gen/src/froidure-pin-pbr.o
   GAC     src/froidure-pin-pperm.cpp => gen/src/froidure-pin-pperm.o
   GAC     src/froidure-pin-transf.cpp => gen/src/froidure-pin-transf.o
   GAC     src/pkg.cpp => gen/src/pkg.o
In file included from src/pkg.cpp:59:
In file included from ./bin/include/libsemigroups/sims1.hpp:1269:
./bin/include/libsemigroups/sims1.tpp:622:39: error: no member named 'long_rules' in 'libsemigroups::Sims1::iterator_base'
  622 |     _longs           = std::move(that.long_rules());
      |                                  ~~~~ ^
1 error generated.
make: *** [gen/src/pkg.o] Error 1
```
libsemigroups 3.0.3 by itself compiles without problem.

Being discussed on the GAP Forum https://lists.uni-kl.de/gap/arc/forum/2025-06/msg00008.html

### PR DESCRIPTION
**Pull request by james-d-mitchell**
Hopefully this resolves #1064, and an issue with `TikzString` for `Bipartitions`.

### CODE REVIEW

**Comment by james-d-mitchell** [comment]
The external ci job fails because v2.7.4 of libsemigroups hasn't been picked up by condo. I think I'll just let that go...
