### ISSUE TITLE
Build problem on Mac OS

### ISSUE THREAD

**Issue by egri-nagy** [semigroups/Semigroups#1064]
Semigroups packages fails to build on Mac OS 15.5.
Compiler:
```
Apple clang version 17.0.0 (clang-1700.0.13.5)
Target: arm64-apple-darwin24.5.0
Thread model: posix
```
Error message:
```
 make
./config.status gen/pkgconfig.h
config.status: creating gen/pkgconfig.h
config.status: gen/pkgconfig.h is unchanged
echo > gen/pkgconfig.h.stamp
   GAC     src/bipart.cpp => gen/src/bipart.o
   GAC     src/cong.cpp => gen/src/cong.o
   GAC     src/conglatt.cpp => gen/src/conglatt.o
   GAC     src/froidure-pin-base.cpp => gen/src/froidure-pin-base.o
   GAC     src/froidure-pin-bipart.cpp => gen/src/froidure-pin-bipart.o
   GAC     src/froidure-pin-bmat.cpp => gen/src/froidure-pin-bmat.o
   GAC     src/froidure-pin-fallback.cpp => gen/src/froidure-pin-fallback.o
   GAC     src/froidure-pin-matrix.cpp => gen/src/froidure-pin-matrix.o
   GAC     src/froidure-pin-max-plus-mat.cpp => gen/src/froidure-pin-max-plus-mat.o
   GAC     src/froidure-pin-min-plus-mat.cpp => gen/src/froidure-pin-min-plus-mat.o
   GAC     src/froidure-pin-pbr.cpp => gen/src/froidure-pin-pbr.o
   GAC     src/froidure-pin-pperm.cpp => gen/src/froidure-pin-pperm.o
   GAC     src/froidure-pin-transf.cpp => gen/src/froidure-pin-transf.o
   GAC     src/pkg.cpp => gen/src/pkg.o
In file included from src/pkg.cpp:59:
In file included from ./bin/include/libsemigroups/sims1.hpp:1269:
./bin/include/libsemigroups/sims1.tpp:622:39: error: no member named 'long_rules' in 'libsemigroups::Sims1::iterator_base'
  622 |     _longs           = std::move(that.long_rules());
      |                                  ~~~~ ^
1 error generated.
make: *** [gen/src/pkg.o] Error 1
```
libsemigroups 3.0.3 by itself compiles without problem.

Being discussed on the GAP Forum https://lists.uni-kl.de/gap/arc/forum/2025-06/msg00008.html

**Comment by james-d-mitchell** [comment]
Thanks for the report @egri-nagy. This is the same issue as reported at:

https://github.com/libsemigroups/libsemigroups/issues/557

There are 3 solutions (from quickest to slowest):

1. The quickest fix (if you just want to get Semigroups to compile) is to just delete that line of code. 
2. The next best fix will be that I release a new version of libsemigroups version 2, which fixes the issue (the stable-2.7 branch of libsemigroups already contains the fixed version of the code). Then release a new version of Semigroups using the new release of libsemigroups.
3. The best fix would be that I update the Semigroups package to work with version 3 of libsemigroups.

I will do 2 as soon as I reasonably can (probably not this week), and am working on 3.

**Comment by egri-nagy** [comment]
>     1. The quickest fix (if you just want to get Semigroups to compile) is to just delete that line of code.

For anyone in a hurry, I can confirm that the quick fix works fine.

**Comment by james-d-mitchell** [comment]
Resolved in v5.5.1 but I'm going to leave this issue open until that's picked up by a GAP release itself (just in case anyone else has this problem).

**Comment by james-d-mitchell** [comment]
Good question, only v2.7.4 at the moment

**Comment by dimpase** [comment]
not v3 at all, right?

**Comment by james-d-mitchell** [comment]
> not v3 at all, right?

Right. We're working on it but it might take a little while.
